language: python
python:
  - "3.10"
  
before_install:
  - sudo apt-get update
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8 gcc-4.8
  - sudo ln -sf /usr/bin/gcc-4.8 /usr/bin/gcc
  - sudo ln -sf /usr/bin/g++-4.8 /usr/bin/g++
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy
  
install:
  - travis_retry pip install coveralls
  - travis_retry pip install -r requirements.txt
  
# command to run tests, e.g. python setup.py test
script: coverage run --source seek setup.py test
after_success:
    coveralls
  